version: '3'
services:
  mongo:
    image: mongo
    restart: always
    ports:
     - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_user
      MONGO_INITDB_ROOT_PASSWORD: mongo_f3984hf0w8j98a87hsfi8e7h4kufyab3j4hyfgau6gwufbax6g763g4ib6gfia673gf
